name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_PATH: OnatrixProject/OnatrixProject.csproj
  PUBLISH_DIR: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM deps
        run: npm ci

      - name: Build CSS (minify)
        run: npm run build

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }} --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./webapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: umbraco-project                 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85CA786C4E8E480B80E27DC0F1817A83 }}
          package: ./webapp

